-- ---------------------------------------------------------------------------
-- demos/04-healthcare-ehr-governed-analytics/01-setup.sql
-- Creates the Healthcare schema objects for the governed analytics demo.
--
-- Feature set exercised here:
--   * Row Access Policies (department and region)
--   * Dynamic Data Masking (PHI fields)
--   * Tag-Based Masking using PII_CLASS
--   * Secure Views inheriting policies
--   * Role scaffolding for the 3-role demonstration
-- ---------------------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- 1. Demo roles (Cardiology analyst, Regional coordinator, masked Data Engineer)
CREATE ROLE IF NOT EXISTS CARDIOLOGY_ANALYST   COMMENT = 'Analyst with access to cardiology encounters only';
CREATE ROLE IF NOT EXISTS REGIONAL_MIDWEST     COMMENT = 'Regional coordinator for Midwest encounters only';
CREATE ROLE IF NOT EXISTS DATA_ENGINEER_MASKED COMMENT = 'Data engineering role with PHI masked';

GRANT ROLE CARDIOLOGY_ANALYST   TO ROLE SYSADMIN;
GRANT ROLE REGIONAL_MIDWEST     TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER_MASKED TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE DEMO_WH TO ROLE CARDIOLOGY_ANALYST;
GRANT USAGE ON WAREHOUSE DEMO_WH TO ROLE REGIONAL_MIDWEST;
GRANT USAGE ON WAREHOUSE DEMO_WH TO ROLE DATA_ENGINEER_MASKED;

GRANT USAGE ON DATABASE SNOWFLAKE_DEMO_PACK TO ROLE CARDIOLOGY_ANALYST;
GRANT USAGE ON DATABASE SNOWFLAKE_DEMO_PACK TO ROLE REGIONAL_MIDWEST;
GRANT USAGE ON DATABASE SNOWFLAKE_DEMO_PACK TO ROLE DATA_ENGINEER_MASKED;

GRANT USAGE ON SCHEMA SNOWFLAKE_DEMO_PACK.HEALTHCARE TO ROLE CARDIOLOGY_ANALYST;
GRANT USAGE ON SCHEMA SNOWFLAKE_DEMO_PACK.HEALTHCARE TO ROLE REGIONAL_MIDWEST;
GRANT USAGE ON SCHEMA SNOWFLAKE_DEMO_PACK.HEALTHCARE TO ROLE DATA_ENGINEER_MASKED;

USE ROLE SYSADMIN;
USE WAREHOUSE DEMO_WH;
USE DATABASE SNOWFLAKE_DEMO_PACK;
USE SCHEMA HEALTHCARE;

-- 2. Encounters base table
CREATE OR REPLACE TABLE PATIENT_ENCOUNTERS (
    ENCOUNTER_ID             STRING        NOT NULL,
    PATIENT_PSEUDONYM        STRING        NOT NULL,
    ENCOUNTER_TIMESTAMP      TIMESTAMP_NTZ NOT NULL,
    DEPARTMENT               STRING        NOT NULL,
    PRIMARY_CONDITION        STRING,
    COMORBIDITY_COUNT        NUMBER(5, 0),
    AGE_DECADE               NUMBER(5, 0),
    GENDER                   STRING,
    REGION                   STRING,
    LENGTH_OF_STAY_DAYS      NUMBER(5, 0),
    READMITTED_WITHIN_30D    BOOLEAN,
    BILLED_AMOUNT_USD        NUMBER(18, 2),
    INSURANCE_TYPE           STRING,
    INGEST_TIMESTAMP         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PATIENT_ENCOUNTERS PRIMARY KEY (ENCOUNTER_ID)
)
CLUSTER BY (ENCOUNTER_TIMESTAMP, DEPARTMENT)
COMMENT = 'De-identified encounter records; clustered for department-filtered queries';

-- 3. Billing claims
CREATE OR REPLACE TABLE BILLING_CLAIMS (
    CLAIM_ID                 STRING        DEFAULT UUID_STRING(),
    ENCOUNTER_ID             STRING        NOT NULL,
    PATIENT_PSEUDONYM        STRING        NOT NULL,
    PAYER                    STRING,
    BILLED_AMOUNT_USD        NUMBER(18, 2),
    ALLOWED_AMOUNT_USD       NUMBER(18, 2),
    CONTRACT_CAPITATION_USD  NUMBER(18, 2),
    CLAIM_STATUS             STRING,
    CONSTRAINT PK_BILLING_CLAIMS PRIMARY KEY (CLAIM_ID)
)
COMMENT = 'Claim-level billing records joined to encounters';

-- 4. PHI masking policy: only privileged roles see patient pseudonyms.
CREATE OR REPLACE MASKING POLICY PHI_MASK AS (VAL STRING)
    RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'DEMO_PACK_ROLE')
            THEN VAL
        WHEN CURRENT_ROLE() IN ('CARDIOLOGY_ANALYST', 'REGIONAL_MIDWEST')
            THEN SHA2(VAL, 256)
        ELSE '***MASKED***'
    END
COMMENT = 'Role-aware masking for patient pseudonyms and free-text columns';

-- 5. Numeric masking for billed amounts (data engineer sees buckets only)
CREATE OR REPLACE MASKING POLICY BILLED_AMOUNT_MASK AS (VAL NUMBER(18, 2))
    RETURNS NUMBER(18, 2) ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'DEMO_PACK_ROLE',
                                 'CARDIOLOGY_ANALYST', 'REGIONAL_MIDWEST')
            THEN VAL
        ELSE ROUND(VAL, -3)  -- round to nearest $1000 for the data engineer role
    END
COMMENT = 'Rounds billed amounts to nearest $1000 for DATA_ENGINEER_MASKED';

-- 6. Department row access policy
CREATE OR REPLACE ROW ACCESS POLICY DEPARTMENT_ACCESS AS (DEPARTMENT_VAL STRING)
    RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'DEMO_PACK_ROLE',
                                 'DATA_ENGINEER_MASKED')
            THEN TRUE
        WHEN CURRENT_ROLE() = 'CARDIOLOGY_ANALYST'
            AND DEPARTMENT_VAL = 'CARDIOLOGY'
            THEN TRUE
        WHEN CURRENT_ROLE() = 'REGIONAL_MIDWEST'
            THEN TRUE
        ELSE FALSE
    END;

-- 7. Region row access policy (applies only to REGIONAL_MIDWEST)
CREATE OR REPLACE ROW ACCESS POLICY REGION_ACCESS AS (REGION_VAL STRING)
    RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'DEMO_PACK_ROLE',
                                 'CARDIOLOGY_ANALYST', 'DATA_ENGINEER_MASKED')
            THEN TRUE
        WHEN CURRENT_ROLE() = 'REGIONAL_MIDWEST' AND REGION_VAL = 'MIDWEST'
            THEN TRUE
        ELSE FALSE
    END;

-- 8. Attach the column masks
ALTER TABLE PATIENT_ENCOUNTERS
    MODIFY COLUMN PATIENT_PSEUDONYM SET MASKING POLICY PHI_MASK,
    MODIFY COLUMN BILLED_AMOUNT_USD SET MASKING POLICY BILLED_AMOUNT_MASK;

ALTER TABLE BILLING_CLAIMS
    MODIFY COLUMN PATIENT_PSEUDONYM  SET MASKING POLICY PHI_MASK,
    MODIFY COLUMN BILLED_AMOUNT_USD  SET MASKING POLICY BILLED_AMOUNT_MASK,
    MODIFY COLUMN ALLOWED_AMOUNT_USD SET MASKING POLICY BILLED_AMOUNT_MASK;

-- 9. Attach the row access policies
ALTER TABLE PATIENT_ENCOUNTERS
    ADD ROW ACCESS POLICY DEPARTMENT_ACCESS ON (DEPARTMENT),
    ADD ROW ACCESS POLICY REGION_ACCESS     ON (REGION);

-- 10. Tag columns with PII class for governance tooling
ALTER TABLE PATIENT_ENCOUNTERS
    MODIFY COLUMN PATIENT_PSEUDONYM SET TAG PII_CLASS = 'HIGH',
    MODIFY COLUMN AGE_DECADE        SET TAG PII_CLASS = 'LOW',
    MODIFY COLUMN GENDER            SET TAG PII_CLASS = 'LOW',
    MODIFY COLUMN REGION            SET TAG PII_CLASS = 'LOW';

ALTER TABLE PATIENT_ENCOUNTERS SET TAG COMPLIANCE_REGIME = 'HIPAA';
ALTER TABLE BILLING_CLAIMS     SET TAG COMPLIANCE_REGIME = 'HIPAA';

-- 11. Secure view for cross-department analytics
CREATE OR REPLACE SECURE VIEW ENCOUNTERS_SECURE AS
SELECT
    E.ENCOUNTER_ID,
    E.PATIENT_PSEUDONYM,
    E.ENCOUNTER_TIMESTAMP,
    E.DEPARTMENT,
    E.PRIMARY_CONDITION,
    E.COMORBIDITY_COUNT,
    E.AGE_DECADE,
    E.GENDER,
    E.REGION,
    E.LENGTH_OF_STAY_DAYS,
    E.READMITTED_WITHIN_30D,
    E.BILLED_AMOUNT_USD,
    E.INSURANCE_TYPE,
    C.PAYER,
    C.CONTRACT_CAPITATION_USD,
    C.CLAIM_STATUS
FROM PATIENT_ENCOUNTERS AS E
LEFT JOIN BILLING_CLAIMS AS C
    ON E.ENCOUNTER_ID = C.ENCOUNTER_ID
COMMENT = 'Policy-inheriting join of encounters and billing claims';

-- 12. Grant analyst roles read access to the secure view only (not the base tables)
GRANT SELECT ON VIEW ENCOUNTERS_SECURE TO ROLE CARDIOLOGY_ANALYST;
GRANT SELECT ON VIEW ENCOUNTERS_SECURE TO ROLE REGIONAL_MIDWEST;
GRANT SELECT ON VIEW ENCOUNTERS_SECURE TO ROLE DATA_ENGINEER_MASKED;

-- 13. Data engineer gets base table too, but PHI is masked by policy
GRANT SELECT ON TABLE PATIENT_ENCOUNTERS TO ROLE DATA_ENGINEER_MASKED;
GRANT SELECT ON TABLE BILLING_CLAIMS     TO ROLE DATA_ENGINEER_MASKED;

-- 14. Audit helper view: last 24h of queries on PATIENT_ENCOUNTERS
CREATE OR REPLACE VIEW PHI_AUDIT_24H AS
SELECT
    QUERY_ID,
    QUERY_START_TIME,
    USER_NAME,
    ROLE_NAME,
    BASE_OBJECTS_ACCESSED,
    DIRECT_OBJECTS_ACCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND BASE_OBJECTS_ACCESSED::STRING ILIKE '%PATIENT_ENCOUNTERS%'
COMMENT = 'Last 24h of queries touching PHI; consumed by compliance';

-- End of 01-setup.sql
